#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = trik/dsp/ov7670/object_sensor/dsp_server
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/trik-dsp/xdctools_3_24_07_73/include/utils.tci:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/include/utils.tci
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xdc.tci:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xdc.tci
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/template.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/template.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/om2.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/om2.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xmlgen.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xmlgen.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xmlgen2.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/xmlgen2.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/IPackage.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/IPackage.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/package.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/package.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/services/global/Clock.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/services/global/Clock.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/services/global/Trace.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/services/global/Trace.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/bld.js:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/bld.js
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/BuildEnvironment.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/PackageContents.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/_gen.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/_gen.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Library.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Library.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Executable.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Executable.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Repository.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Repository.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Configuration.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Configuration.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Script.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Script.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Manifest.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Manifest.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Utils.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/Utils.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITarget.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITarget.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITarget2.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITarget2.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/ITargetFilter.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/package.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/xdc/bld/package.xs
package.mak: config.bld
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/ITarget.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/ITarget.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/C28_large.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/C28_large.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/C28_float.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/C28_float.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/package.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/package.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/elf/ITarget.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/elf/ITarget.xs
/opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/elf/package.xs:
package.mak: /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/elf/package.xs
package.mak: package.bld
endif

ti.targets.elf.C674.rootDir ?= /opt/trik-dsp/cgt_c6000_7.4.2
ti.targets.elf.packageBase ?= /opt/trik-dsp/xdctools_3_24_07_73/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_trik.dsp.ov7670.object_sensor.dsp_server.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package trik.dsp.ov7670.object_sensor.dsp_server" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,e674 .dlls: bin/dsp_server.pe674

-include package/cfg/bin/dsp_server_pe674.mak
-include package/cfg/bin/dsp_server_pe674.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/bin/dsp_server_pe674.dep
endif
bin/dsp_server.pe674: package/cfg/bin/dsp_server_pe674.xdl
	@


ifeq (,$(wildcard .libraries,e674))
bin/dsp_server.pe674 package/cfg/bin/dsp_server_pe674.c: .libraries,e674
endif

package/cfg/bin/dsp_server_pe674.c package/cfg/bin/dsp_server_pe674.h package/cfg/bin/dsp_server_pe674.xdl: override _PROG_NAME := bin/dsp_server.xe674
package/cfg/bin/dsp_server_pe674.c: package/cfg/bin/dsp_server_pe674.cfg

clean:: clean,e674
	-$(RM) package/cfg/bin/dsp_server_pe674.cfg
	-$(RM) package/cfg/bin/dsp_server_pe674.dep
	-$(RM) package/cfg/bin/dsp_server_pe674.c
	-$(RM) package/cfg/bin/dsp_server_pe674.xdc.inc

clean,e674::
	-$(RM) bin/dsp_server.pe674
.executables,e674 .executables: bin/dsp_server.xe674

bin/dsp_server.xe674: |bin/dsp_server.pe674

-include package/cfg/bin/dsp_server.xe674.mak
bin/dsp_server.xe674: package/cfg/bin/dsp_server_pe674.oe674 
	$(RM) $@
	@$(MSG) lnke674 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.elf.C674.rootDir)/bin/lnk6x -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@) -l link.cmd -q -o $@ package/cfg/bin/dsp_server_pe674.oe674  package/cfg/bin/dsp_server/main.oe674  package/cfg/bin/dsp_server_pe674.xdl --abi=eabi -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.elf.C674.rootDir)/lib/rts6740_elf.lib
	
bin/dsp_server.xe674: export C_DIR=
bin/dsp_server.xe674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

bin/dsp_server.test test,e674 test: bin/dsp_server.xe674.test

bin/dsp_server.xe674.test:: bin/dsp_server.xe674
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 bin/dsp_server.xe674.test
else
	@$(MSG) running $<  ...
	$(call EXEC.bin/dsp_server.xe674, ) 
endif

clean,e674::
	-$(RM) bin/.tmp,dsp_server.xe674,0,*


clean:: clean,e674

clean,e674::
	-$(RM) bin/dsp_server.xe674
clean:: 
	-$(RM) package/cfg/bin/dsp_server_pe674.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
dsp_server_pe674.oe674,copy : package/cfg/bin/dsp_server_pe674.oe674
dsp_server_pe674.se674,copy : package/cfg/bin/dsp_server_pe674.se674
main.oe674,copy : package/cfg/bin/dsp_server/main.oe674
main.se674,copy : package/cfg/bin/dsp_server/main.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,trik_dsp_ov7670_object_sensor_dsp_server
trik_dsp_ov7670_object_sensor_dsp_server.tar: package/package.bld.xml
trik_dsp_ov7670_object_sensor_dsp_server.tar: package/build.cfg
trik_dsp_ov7670_object_sensor_dsp_server.tar: package/package.xdc.inc
trik_dsp_ov7670_object_sensor_dsp_server.tar: bin/dsp_server.xe674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/trik_dsp_ov7670_object_sensor_dsp_server.tar.dep
endif
package/rel/trik_dsp_ov7670_object_sensor_dsp_server/trik/dsp/ov7670/object_sensor/dsp_server/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

trik_dsp_ov7670_object_sensor_dsp_server.tar: package/rel/trik_dsp_ov7670_object_sensor_dsp_server.xdc.inc package/rel/trik_dsp_ov7670_object_sensor_dsp_server/trik/dsp/ov7670/object_sensor/dsp_server/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/trik_dsp_ov7670_object_sensor_dsp_server.xdc.inc,package/rel/trik_dsp_ov7670_object_sensor_dsp_server.tar.dep)


release release,trik_dsp_ov7670_object_sensor_dsp_server: all trik_dsp_ov7670_object_sensor_dsp_server.tar
clean:: .clean
	-$(RM) trik_dsp_ov7670_object_sensor_dsp_server.tar
	-$(RM) package/rel/trik_dsp_ov7670_object_sensor_dsp_server.xdc.inc
	-$(RM) package/rel/trik_dsp_ov7670_object_sensor_dsp_server.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) bin/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard bin))
    $(shell $(MKDIR) bin)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/cfg/bin))
    $(shell $(MKDIR) package/cfg/bin)
endif
ifeq (,$(wildcard package/cfg/bin/dsp_server))
    $(shell $(MKDIR) package/cfg/bin/dsp_server)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/trik.dsp.ov7670.object_sensor.dsp_server.pjt
